CardControl/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('<int:pk>/detail/', views.CardDetailView.as_view()),
    path('<int:pk>/detail/change-status/', views.ChangeStatusView.as_view()),
    path('<int:pk>/detail/delete/', views.DeleteCardView.as_view()),
    path('<int:pk>/detail/edit/', views.UpdateCardView.as_view()),
    path('create-card/', views.CreateCardView.as_view()),
    path('generate-cards/', views.GenerateCardsView.as_view()),
    path('__debug__/', include('debug_toolbar.urls')),
]

core/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class Card(models.Model):
    series = models.CharField(max_length=3)
    number = models.PositiveBigIntegerField()
    release_date = models.DateTimeField()
    activity_end_date = models.DateTimeField()
    cvv = models.IntegerField()
    funds = models.IntegerField()
    status = models.CharField(max_length=30)

    def __str__(self):
        return self.number.__str__()


class Purchase(models.Model):
    title = models.CharField(max_length=30)
    price = models.IntegerField()
    address = models.CharField(max_length=255)
    card = models.ForeignKey('Card', on_delete=models.CASCADE)

    def __str__(self):
        return self.card.number.__str__()

core/forms.py
from django import forms

from core.models import Card


class CreateCardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = "__all__"
        widgets = {
            "release_date": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "activity_end_date": forms.DateTimeInput(attrs={"type": "datetime-local"})
        }

    def clean_number(self):
        number = self.cleaned_data['number']
        if len(str(number)) != 16:
            raise forms.ValidationError("Not correct number, number has less or greater 16 digit", code="invalid")

        if Card.objects.filter(number=number).exists():
            raise forms.ValidationError("This card exist in database", code="invalid")

        return number

core/views.py
import random
from datetime import datetime

from django.utils import timezone

from core.models import Card
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from dateutil.relativedelta import relativedelta
from django.views.generic import ListView, DetailView, DeleteView, TemplateView, FormView, UpdateView
from core.forms import CreateCardForm
from core.service import get_random_card_cvv, get_random_card_number
# Create your views here.


class IndexView(ListView):
    template_name = "index.html"
    model = Card
    paginate_by = 10


class CardDetailView(DetailView):
    template_name = "card-detail.html"
    model = Card


class ChangeStatusView(DetailView):
    template_name = "card-detail.html"
    model = Card

    def post(self, request, pk):
        card = Card.objects.get(id=pk)
        if card.status.lower() == "active":
            card.status = "Inactive"
        elif card.status.lower() == "inactive":
            card.status = "Active"

        card.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class DeleteCardView(DeleteView):
    template_name = "card_confirm_delete.html"
    model = Card
    success_url = "/"


class CreateCardView(FormView):
    template_name = "create-card.html"
    form_class = CreateCardForm

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        context = self.get_context_data()
        form = self.get_form(form_class)
        context['form'] = form
        if form.is_valid():
            form.save()
            return redirect("/")

        return self.render_to_response(context)


class UpdateCardView(UpdateView):
    model = Card
    fields = "__all__"
    template_name = "edit-card.html"
    success_url = "/"


class GenerateCardsView(TemplateView):
    template_name = "generate-cards.html"

    def post(self, request):
        series = request.POST.get("series")
        count = int(request.POST.get("count"))
        period = int(request.POST.get("period"))
        year_or_month = request.POST.get("rad")
        today = timezone.now()

        activity_end_date = today + relativedelta(months=1)

        if year_or_month.lower() == "month":
            activity_end_date = today + relativedelta(months=period)
        elif year_or_month.lower() == "year":
            activity_end_date = today + relativedelta(years=period)

        for iterator in range(count):
            card = Card.objects.create(
                series=series,
                number=get_random_card_number(),
                release_date=today,
                cvv=get_random_card_cvv(),
                funds=random.randint(1, 1_000_000),
                activity_end_date=activity_end_date,
                status="Active"
            )
            card.save()
        return redirect("/")

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Main page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous">
    {% block css %}{% endblock %}
</head>
<body class="bg-light">
<div class="container">
    <header class="d-flex justify-content-center py-3 mb-5">
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="/create-card" class="nav-link">Create card</a></li>
            <li class="nav-item"><a href="/generate-cards" class="nav-link">Generate card</a></li>
        </ul>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>
    </header>

    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/card-detail.html
{% extends 'base.html' %}
{% load core_tags %}

{% block content %}
    <div class="card w-75 mx-auto">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4 class="card-title">Series: <u>{{ card.series }}</u></h4>
                <div class="d-flex justify-content-between">
                    <form action="{{ request.path }}delete">{% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete card</button>
                    </form>
                    <a href="{{ request.path }}edit" class="btn btn-warning mx-3">Edit card</a>
                </div>
            </div>

            <h5 class="card-title">Number: <u>{{ card.number|wrapper }}</u></h5>
            <h5 class="card-title">CVV: <u>{{ card.cvv }}</u></h5>
            <p class="card-text">Card release date: <u>{{ card.release_date|convert_date }}</u></p>
            <p class="card-text">Date activity end: <u>{{ card.activity_end_date|convert_date }}</u></p>
            <div class="d-flex justify-content-between">
                <div class="col">
                    <p class="card-text">Funds: <u>{{ card.funds }} UAH</u></p>
                </div>
                <div class="col">
                    <p class="card-text text-end mx-4">
                        Status:
                        <u class="fw-bold {{ card.status|get_color }}">
                            {{ card.status.capitalize }}
                        </u>
                    </p>
                </div>
                <form action="{{ request.path }}change-status/" method="post">{% csrf_token %}
                    {% if card.status.lower == "active" %}
                        <button type="submit" class="btn btn-warning">Deactivate</button>
                    {% elif card.status.lower == "inactive" %}
                        <button type="submit" class="btn btn-success">Activate</button>
                    {% endif %}
                </form>
            </div>
        </div>
        <div class="card-footer">
            <h4 class="card-title">History</h4>
            <ul class="list-group list-group-flush">
                {% for purchase in card.purchase_set.all %}
                    <li class="list-group-item mb-2">
                        <p>Title: <b>{{ purchase.title }}</b></p>
                        <p>Price: <b>-{{ purchase.price }} UAH</b></p>
                        <p>Address: <b>{{ purchase.address }}</b></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/card_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert">
        <form method="post" class="d-flex-column text-center">{% csrf_token %}
            <h3>Are you sure you want to delete card"{{ object }}"?</h3>
            {{ form }}
            <input type="submit" value="Confirm" class="btn btn-danger">
        </form>
    </div>

{% endblock %}

templates/create-card.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block css %}
    <style>
        .form-group {
            margin-bottom: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-8">
            <form action="" method="post">{% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary w-100">Create</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/edit-card.html
{% extends 'create-card.html' %}

templates/generate-cards.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="post">{% csrf_token %}
                <input type="text" class="form-control mb-3" maxlength="3" name="series" placeholder="Write series">
                <input type="number" class="form-control mb-3" name="count" min="1" max="100" placeholder="Write count">
                <div class="d-flex">
                    <input type="number" class="form-control mb-3" name="period" placeholder="Write period">
                    <input type="radio" class="custom-control-input" checked name="rad" value="month" id="month"><label for="month">Month</label>
                    <input type="radio" class="custom-control-input" name="rad" value="year" id="year"><label for="year">Year</label>
                </div>
                <button type="submit" class="btn btn-primary w-100">Generate</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load core_tags %}

{% block content %}
    <div class="row">
        {% for card in page_obj %}
            <div class="col-sm-3 py-3">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{ card.series }}</h4>
                        <h5 class="card-title">{{ card.number|wrapper }}</h5>
                        <div class="row mb-3">
                            <p class="card-text">{{ card.activity_end_date|convert_date }}</p>
                            <div class="col">
                                <p class="card-text">{{ card.funds }} UAH</p>
                            </div>
                            <div class="col">
                                <p class="card-text fw-bold text-center {{ card.status|get_color }}">
                                    {{ card.status.capitalize }}
                                </p>
                            </div>
                        </div>
                        <a href="/{{ card.id }}/detail" class="btn btn-primary">Detail</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex flex-column align-items-center mt-5">
        <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        <ul class="pagination">
            <li class="page-item">
                <a href="?page=1" class="page-link">&laquo; first</a>
            </li>
            <li class="page-item">
                <a class="page-link"
                        {% if page_obj.has_previous %}
                   href="?page={{ page_obj.previous_page_number }}"
                        {% else %}
                   disabled
                        {% endif %}
                >
                    Previous
                </a>
            </li>

            {% for page in paginator.page_range %}
                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}

            <li class="page-item">
                <a class="page-link"
                        {% if page_obj.has_next %}
                   href="?page={{ page_obj.next_page_number }}"
                        {% else %}
                   disabled
                        {% endif %}
                >
                    Next
                </a>
            </li>
            <li class="page-item">
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">last &raquo;</a>
            </li>
        </ul>
    </div>
{% endblock %}